board/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

challengeboard/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('board.urls', namespace='board')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

board/models.py
from django.db import models


class Challenge(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField(blank=True)
    location = models.CharField(max_length=300, blank=True, null=True)
    datetime = models.DateTimeField(blank=True, null=True)
    datetime_end = models.DateTimeField(verbose_name='End date', blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    mode = models.CharField(max_length=100, choices=(
        ('max', 'Highest value wins'),
        ('min', 'Lowest value wins'),
        ('first', 'First entry wins'),
    ))
    value_unit = models.CharField(max_length=300, null=True, blank=True)

    def __str__(self):
        return self.title

    def get_highscore(self):
        if self.mode == 'max':
            order = '-value'
            val = lambda p: p.value
        elif self.mode == 'min':
            order = 'value'
            val = lambda p: p.value
        elif self.mode == 'first':
            self.mode = '-datetime'
            val = lambda p: p.datetime
        ps = list(self.participants.order_by(order))
        curval = None
        curpos = 0
        for p in ps:
            if curval is None or val(p) != curval:
                curpos += 1
                curval = val(p)
            p.pos = curpos
        return ps


class Participant(models.Model):
    challenge = models.ForeignKey(Challenge, related_name="participants")
    name = models.CharField(max_length=300)
    value = models.FloatField(null=True, blank=True)
    datetime = models.DateTimeField()

    def __str__(self):
        return self.name

board/views.py
from django.shortcuts import render, get_object_or_404
from .models import Challenge
import markdown

def index(request):
    ctx = {
        'challenges': Challenge.objects.all().order_by('datetime').prefetch_related('participants')
    }
    for c in ctx['challenges']:
        c.descr = markdown.markdown(c.description)
    return render(request, 'board/index.html', ctx)

challengeboard/board/views.py
from django.shortcuts import render

# Create your views here.

templates/board/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8">
    <title>MRMCD2015 challenges</title>
    <meta name="viewport" content="width=device-width">
    <link rel="shortcut icon" href="https://mrmcd.net/2015/img/favicon.ico" type="image/x-icon" />

    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="https://mrmcd.net/2015/css/style.css">
    <style>
        .container {
            margin: 0 auto;
            padding: 0;
        }
    </style>

</head>
<body>
<div class="container">
    <header>
        <img src="https://mrmcd.net/2015/logo-web.svg">
    </header>
</div>
<div class="navbar">
    <nav class="container">
        <ul>
            <li class="current_page_item">
                <a href="{% url 'board:index' %}">Challenges</a>
            </li>
            <li class="">
                <a href="https://mrmcd.net/2015/">To the event website</a>
            </li>
            <li class="mobile-hidden">
                <a>&nbsp;</a>
            </li>
            <li class="mobile-hidden">
                <a>&nbsp;</a>
            </li>
            <li class="mobile-hidden">
                <a>&nbsp;</a>
            </li>
        </ul>
    </nav>
</div>

<div class="container content hyphenate">
    {% block content %}

    {% endblock %}
</div>
<footer class="navbar">
    <nav class="container">
        <ul>
            <li><a>MRMCD e.V.</a></li>
            <li>
                <a href="https://mrmcd.net/2015/impressum.html">Impressum</a>
            </li>
            <li>
                <a href="https://twitter.com/mrmcd15">
                    <img src="https://mrmcd.net/2015/img/twitter.svg" alt="Twitter" />
                    <span class="mobile-only">@MRMCD15</span>
                </a>
            </li>
            <li class="mobile-hidden"><a>&nbsp;</a></li>
            <li class="mobile-hidden"><a>&nbsp;</a></li>
        </ul>
    </nav>
</footer>
<script src="{% static "js/jquery.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
</body>
</html>

templates/board/index.html
{% extends "board/base.html" %}

{% block content %}
    <h1>Challenges</h1>
    <p>
        At MRMCD15, there will be multiple challenges for you of very different types.
        For some challenges, you might need muscles in your arms, for others, you'll
        rather need them in the brain. There will be challenges with and without sports,
        and challenges with and without computers. Some challenges run during the whole
        event, others happen at a special place and time.
    </p>
    <p>
        Every challenge can be won be exactly one person and will be rewarded with endless
        honor and, of course, a price from the event crew, that will be awarded at the
        event's closing ceremony.
    </p>
    <h2>List of challenges</h2>
    <div class="panel-group">
        {% for c in challenges %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="pull-right">
                        <i class="glyphicon glyphicon-time"></i>
                        {% if c.datetime %}
                            {{ c.datetime|date:"D H:i" }}
                            {% if c.datetime_end %}
                                – {{ c.datetime_end|date:"D H:i" }}
                            {% endif %}
                        {% else %}
                            All time
                        {% endif %}
                    </div>
                    <h4 class="panel-title">
                        <a data-toggle="collapse" href="#challenge{{ c.id }}">
                            {{ c.title }}
                        </a>
                    </h4>
                </div>
                <div id="challenge{{ c.id }}" class="panel-collapse collapse">
                    <div class="panel-body">
                        {% if c.location %}
                            <p>
                                <i class="glyphicon glyphicon-flag" data-tooltip="Ort"></i>
                                {{ c.location }}
                            </p>
                        {% endif %}
                        {% if c.url %}
                            <p>
                                <i class="glyphicon glyphicon-globe"></i>
                                <a href="{{ c.url }}">{{ c.url }}</a>
                            </p>
                        {% endif %}
                        {% if c.description %}
                            <p>
                                {{ c.descr|safe }}
                            </p>
                        {% endif %}
                        {% if c.participants|length > 0 %}
                            <p>
                                <strong>Current Highscore</strong>
                            </p>
                            <table class="table table-condensed table-striped">
                                {% for p in c.get_highscore %}
                                    <tr>
                                        <td>{{ p.pos }}</td>
                                        <td>{{ p.name }}</td>
                                        <td>
                                            {% if challenge.mode == "first" %}
                                                {{ p.datetime|date:"D H:i" }}
                                            {% else %}
                                                {{ p.value }}
                                                {% if challenge.value_unit %}{{ challenge.value_unit }}{% endif %}
                                            {% endif %}
                                        </td>
                                    </tr>

                                {% endfor %}
                            </table>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}